version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
            - ./code:/var/www/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:8.2.2-fpm
        volumes:
            - ./code:/var/www/html
            - ./tmp:/tmp
            - ./ini:/usr/local/etc/php
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
